// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacancyProject.Databases;

#nullable disable

namespace VacancyProject.Migrations
{
    [DbContext(typeof(VacancyDbContext))]
    partial class VacancyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("VacancyProject.Models.JobTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Backend Developer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Frontend Developer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fullstack Developer"
                        });
                });

            modelBuilder.Entity("VacancyProject.Models.Jobseeker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobTitleId");

                    b.ToTable("Jobseekers");
                });

            modelBuilder.Entity("VacancyProject.Models.JobseekerTag", b =>
                {
                    b.Property<int>("JobseekerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobseekerId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("JobseekerTags");
                });

            modelBuilder.Entity("VacancyProject.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Next.js"
                        },
                        new
                        {
                            Id = 5,
                            Name = "React.js"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Typescript"
                        },
                        new
                        {
                            Id = 7,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 8,
                            Name = "ASP.NET"
                        },
                        new
                        {
                            Id = 9,
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Javascript"
                        });
                });

            modelBuilder.Entity("VacancyProject.Models.Jobseeker", b =>
                {
                    b.HasOne("VacancyProject.Models.JobTitle", "JobTitle")
                        .WithMany("Jobseekers")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("VacancyProject.Models.JobseekerTag", b =>
                {
                    b.HasOne("VacancyProject.Models.Jobseeker", "Jobseeker")
                        .WithMany("JobseekerTags")
                        .HasForeignKey("JobseekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VacancyProject.Models.Tag", "Tag")
                        .WithMany("JobseekerTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jobseeker");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VacancyProject.Models.JobTitle", b =>
                {
                    b.Navigation("Jobseekers");
                });

            modelBuilder.Entity("VacancyProject.Models.Jobseeker", b =>
                {
                    b.Navigation("JobseekerTags");
                });

            modelBuilder.Entity("VacancyProject.Models.Tag", b =>
                {
                    b.Navigation("JobseekerTags");
                });
#pragma warning restore 612, 618
        }
    }
}
